# Generated by Django 5.1.5 on 2025-01-25 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='book',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
